<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="pragma" content="no-cache" />

<meta charset="utf-8" />

<!--[if lt IE 9]>
<script src="{$asset_path}/html5shiv.js"></script>
<![endif]-->

<link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" />
<link href="{$asset_path}/styles.css" rel="stylesheet" />

<script src="{$asset_path}/jquery-1.10.2.min.js"></script>
<script src="{$asset_path}/mediatizr-0.3.0.Sheethub.W.min.js"></script>
